context:
  name: reptyr
  version: "0.10.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/nelhage/${{ name }}/archive/refs/tags/${{ name }}-${{ version }}.tar.gz
  sha256: c6ffbc34a511ac00d072219bda30699e51f2f4eb483cbae9e32e981d49e8b380
build:
  script: make install PREFIX=$PREFIX BASHCOMPDIR=$PREFIX/share/bash/completions/
  number: 0
  skip: not linux

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - make

tests:
  - script: reptyr -help

about:
  homepage: https://github.com/nelhage/reptyr
  summary: 'Reparent a running program to a new terminal'
  description: reptyr is a utility for taking an existing running program and attaching it to a new terminal. Started a long-running process over ssh, but have to leave and don't want to interrupt it? Just start a screen, use reptyr to grab it, and then kill the ssh session and head on home.
  license: MIT
  license_file: COPYING
  repository: https://github.com/nelhage/reptyr

extra:
  recipe-maintainers:
    - EllaBootQC
